### PR TITLE
bump build number

### PR DESCRIPTION
**Pull request by ocefpaf**
Ping @gillins

### CODE REVIEW

**Comment by gillins** [comment]
Thanks @ocefpaf!

**Comment by ocefpaf** [comment]
@gillins I will move the other `kealib` build numbers to a "broken" label to avoid exposing them to `conda`. (conda does not see build number as most users expects and a lower one can be chosen and downloaded in lieu of the latest one.)

**Comment by gillins** [comment]
Thanks @ocefpaf - much appreciated. Will try and leave `kealib` alone for a while now....

**Comment by ocefpaf** [comment]
Don't worry about that :smile: 

When it comes to `gdal` and its tons of dependencies this is unavoidable.  We need to move to `conda-build 3` and issues like this will be easier to deal with.

**Pull request merged**
