### PR TITLE
Pin poppler

### PR DESCRIPTION
**Pull request by snowman2**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`

Addresses issue #56

### CODE REVIEW

**Comment by snowman2** [comment]
@conda-forge-admin, please rerender.

**Comment by ocefpaf** [comment]
@snowman2 pins are no longer handled that way. We should check we the ABI breakages happened there and pin it here:

https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/conda_build_config.yaml#L397-L398 

https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/conda_build_config.yaml#L202-L203

Note that according to the ABI laboratory,

https://abi-laboratory.pro/?view=timeline&l=poppler ,

the current pinning should be OK but I see you are experiencing issues in #56 

Ping @isuruf, @pkgw, and @dougalsutherland who may have a better insight on the issue.

**Comment by snowman2** [comment]
That's good to know pins have changed. I will pin it on my local instance for now. Thanks!

**Comment by ocefpaf** [comment]
> That's good to know pins have changed.

That file should make it easier to control pins for the whole ecosystem. Note that we can still override that for special cases. However, I'm not convinced that the issue you are experiencing is due to the pinning, something else may be at play there.

**Pull request closed without merging**
