### PR TITLE
WIP: rebuild 2.3.1

### PR DESCRIPTION
**Pull request by gillins**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [x] Ensured the license file is being packaged.

Attempt to resolve build issues on OSX with dependent packages (see https://github.com/conda-forge/rios-feedstock/pull/15).

### CODE REVIEW

**Comment by gillins** [comment]
@conda-forge-admin, please rerender

**Comment by ocefpaf** [comment]
Are you building `rios` against `2.3.1` or `2.2.4`??

**Comment by gillins** [comment]
`2.3.1`. Well `rios` has no pinning to `gdal` since it is pure Python (see https://github.com/conda-forge/rios-feedstock/pull/10) but it seems the solver defaults to the highest available version. So I guess this problem on OSX doesn't cause much of a problem at the moment since not many packages are using 2.3.1 (yet).

**Comment by gillins** [comment]
Still looks like we have the same problem...

**Comment by ocefpaf** [comment]
To increase the issue visibility here is the env on OS X for the build here:

```
# Name                    Version                   Build  Channel
anaconda-client           1.7.1                      py_0    conda-forge
asn1crypto                0.24.0                   py36_0    defaults
beautifulsoup4            4.6.1                    py36_0    conda-forge
ca-certificates           2018.4.16                     0    conda-forge
certifi                   2018.4.16                py36_0    conda-forge
cffi                      1.11.5           py36h342bebf_0    defaults
chardet                   3.0.4            py36h96c241c_1    defaults
clyent                    1.2.2                      py_1    conda-forge
conda                     4.5.9                    py36_0    conda-forge
conda-build               3.12.0                   py36_2    conda-forge
conda-env                 2.6.0                h36134e3_0    defaults
conda-forge-ci-setup      1.3.5                         0    conda-forge
cryptography              2.2.2            py36h1de35cc_0    defaults
decorator                 4.3.0                      py_0    conda-forge
filelock                  3.0.4                      py_1    conda-forge
glob2                     0.6                        py_0    conda-forge
idna                      2.6              py36h8628d0a_1    defaults
ipython_genutils          0.2.0                      py_1    conda-forge
jinja2                    2.10                       py_1    conda-forge
jsonschema                2.6.0                    py36_1    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
libcxx                    4.0.1                h579ed51_0    defaults
libcxxabi                 4.0.1                hebd6815_0    defaults
libedit                   3.1.20170329         hb402a30_2    defaults
libffi                    3.2.1                h475c297_4    defaults
markupsafe                1.0                      py36_0    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
ncurses                   6.1                  h0a44026_0    defaults
openssl                   1.0.2o               h470a237_1    conda-forge
pip                       10.0.1                   py36_0    defaults
pkginfo                   1.4.2                      py_1    conda-forge
psutil                    5.4.6                    py36_0    conda-forge
pycosat                   0.6.3            py36hee92d8f_0    defaults
pycparser                 2.18             py36h724b2fc_1    defaults
pyopenssl                 18.0.0                   py36_0    defaults
pysocks                   1.6.8                    py36_0    defaults
python                    3.6.5                hc167b69_1    defaults
python-dateutil           2.7.3                      py_0    conda-forge
python.app                2                        py36_8    defaults
pytz                      2018.5                     py_0    conda-forge
pyyaml                    3.12                     py36_1    conda-forge
readline                  7.0                  hc1231fa_4    defaults
requests                  2.18.4           py36h4516966_1    defaults
ruamel_yaml               0.15.37          py36h1de35cc_2    defaults
setuptools                39.2.0                   py36_0    defaults
six                       1.11.0           py36h0e22d5e_1    defaults
sqlite                    3.23.1               hf1716c9_0    defaults
tk                        8.6.7                h35a86e2_3    defaults
traitlets                 4.3.2                    py36_0    conda-forge
urllib3                   1.22             py36h68b9469_0    defaults
wheel                     0.31.1                   py36_0    defaults
xz                        5.2.4                h1de35cc_4    defaults
yaml                      0.1.7                hc338f04_2    defaults
zlib                      1.2.11               hf3cbc9b_2    defaults
```

Even `python` is coming from `defaults` :-( even though we have multiple versions of 3.6 with various pinning, sure on of those would be OK if we could clear the `defaults` packages.

We need to work around `conda` here and find what packages need to be updated to fix this for good. Or we can wait for the compiler migration (ping @CJ-Wright :wink:) because that will rebuild everything anyway.

**Comment by gillins** [comment]
Closed in favour of #59

**Comment by ocefpaf** [comment]
I'm working on `2.2.4` so this one is also needed, but we can wait until I figure out what needs to be rebuild on OS X to get the right set of packages there.

**Comment by kmuehlbauer** [comment]
@ocefpaf The build after merge is broken, so this package didn't got into play. https://circleci.com/gh/conda-forge/libgdal-feedstock/tree/master

**Comment by ocefpaf** [comment]
This PR fixed 2.2.4 series. I'm working on 2.3.1 today :grimacing: 

(And I still need to fix the Windows uploads on the 2.2.4 :smile:)

**Comment by kmuehlbauer** [comment]
A bit confusing, master is 2.3.1, isn't it? :grimacing:

**Comment by ocefpaf** [comment]
Oh. Yes, sorry. This is @gillins PR and not mine at #60 

(I'm answering a tons of issues this morning.)

Still, I'm getting to this in a moment.

**Comment by kmuehlbauer** [comment]
No worries! Doing other stuff in the meantime :+1:

**Pull request merged**
